/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module LAB1_CS303 (
  input x3,
  input x2,
  input x1,
  input x0,
  output out
);
  assign out = ((~ x3 & ~ x2 & x1) | (~ x3 & x2 & x0) | (x2 & ~ x1 & x0) | (~ x2 & x1 & x0));
endmodule
